/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardNotesIndexRouteImport } from './routes/dashboard/notes/index'
import { Route as DashboardBoardsIndexRouteImport } from './routes/dashboard/boards/index'
import { Route as DashboardNotesCreateRouteImport } from './routes/dashboard/notes/create'
import { Route as DashboardBoardsCreateRouteImport } from './routes/dashboard/boards/create'
import { Route as DashboardBoardsIdRouteImport } from './routes/dashboard/boards/$id'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotesIndexRoute = DashboardNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBoardsIndexRoute = DashboardBoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotesCreateRoute = DashboardNotesCreateRouteImport.update({
  id: '/notes/create',
  path: '/notes/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBoardsCreateRoute = DashboardBoardsCreateRouteImport.update({
  id: '/boards/create',
  path: '/boards/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBoardsIdRoute = DashboardBoardsIdRouteImport.update({
  id: '/boards/$id',
  path: '/boards/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/boards/$id': typeof DashboardBoardsIdRoute
  '/dashboard/boards/create': typeof DashboardBoardsCreateRoute
  '/dashboard/notes/create': typeof DashboardNotesCreateRoute
  '/dashboard/boards': typeof DashboardBoardsIndexRoute
  '/dashboard/notes': typeof DashboardNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/boards/$id': typeof DashboardBoardsIdRoute
  '/dashboard/boards/create': typeof DashboardBoardsCreateRoute
  '/dashboard/notes/create': typeof DashboardNotesCreateRoute
  '/dashboard/boards': typeof DashboardBoardsIndexRoute
  '/dashboard/notes': typeof DashboardNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/boards/$id': typeof DashboardBoardsIdRoute
  '/dashboard/boards/create': typeof DashboardBoardsCreateRoute
  '/dashboard/notes/create': typeof DashboardNotesCreateRoute
  '/dashboard/boards/': typeof DashboardBoardsIndexRoute
  '/dashboard/notes/': typeof DashboardNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/boards/$id'
    | '/dashboard/boards/create'
    | '/dashboard/notes/create'
    | '/dashboard/boards'
    | '/dashboard/notes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/boards/$id'
    | '/dashboard/boards/create'
    | '/dashboard/notes/create'
    | '/dashboard/boards'
    | '/dashboard/notes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/boards/$id'
    | '/dashboard/boards/create'
    | '/dashboard/notes/create'
    | '/dashboard/boards/'
    | '/dashboard/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notes/': {
      id: '/dashboard/notes/'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/boards/': {
      id: '/dashboard/boards/'
      path: '/boards'
      fullPath: '/dashboard/boards'
      preLoaderRoute: typeof DashboardBoardsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notes/create': {
      id: '/dashboard/notes/create'
      path: '/notes/create'
      fullPath: '/dashboard/notes/create'
      preLoaderRoute: typeof DashboardNotesCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/boards/create': {
      id: '/dashboard/boards/create'
      path: '/boards/create'
      fullPath: '/dashboard/boards/create'
      preLoaderRoute: typeof DashboardBoardsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/boards/$id': {
      id: '/dashboard/boards/$id'
      path: '/boards/$id'
      fullPath: '/dashboard/boards/$id'
      preLoaderRoute: typeof DashboardBoardsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBoardsIdRoute: typeof DashboardBoardsIdRoute
  DashboardBoardsCreateRoute: typeof DashboardBoardsCreateRoute
  DashboardNotesCreateRoute: typeof DashboardNotesCreateRoute
  DashboardBoardsIndexRoute: typeof DashboardBoardsIndexRoute
  DashboardNotesIndexRoute: typeof DashboardNotesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBoardsIdRoute: DashboardBoardsIdRoute,
  DashboardBoardsCreateRoute: DashboardBoardsCreateRoute,
  DashboardNotesCreateRoute: DashboardNotesCreateRoute,
  DashboardBoardsIndexRoute: DashboardBoardsIndexRoute,
  DashboardNotesIndexRoute: DashboardNotesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
